services:
  apache:
    image: tugboatqa/httpd
    default: true
    commands:
      init:
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
    urls:
      # Create visual diffs of the these URLs using the default options
      - /
      - /about.html
    visualdiff:
      threshold: 90
  mysql:
    image: tugboatqa/mysql:5.6
